const challenges=[
{title:"Le mail impossible",situation:"Vous êtes cadre de santé. Vous devez annoncer à votre équipe une modification du planning qui entraîne des changements de poste pour plusieurs professionnels. Vous souhaitez expliquer la décision tout en limitant les tensions et en maintenant une relation de confiance.",mission:"Construisez un prompt RCTF permettant à votre IA de rédiger le message destiné à l’équipe. Le résultat doit être suffisamment professionnel pour servir de base à un message réel."},
{title:"Le briefing d’équipe",situation:"Vous êtes cadre de santé. Votre équipe connaît actuellement des tensions liées à la charge de travail et à la répartition des tâches. Plusieurs professionnels expriment leur sentiment de ne pas être entendus.",mission:"Demandez à l’IA de vous aider à préparer votre prochain briefing d’équipe : objectifs, déroulement, questions à poser, points de vigilance et pistes pour faire émerger des solutions."},
{title:"Le boss final",situation:"Vous êtes cadre de santé dans un service hospitalier. Vous devez préparer un entretien avec un professionnel dont les retards sont devenus fréquents depuis plusieurs semaines. Le professionnel est compétent et apprécié de l’équipe, mais la situation commence à avoir des conséquences sur l’organisation du service.",mission:"Utilisez l’IA pour préparer cet entretien. Votre résultat doit comporter : les objectifs de l’entretien, une formulation pour aborder le problème, des questions ouvertes, les réactions défensives possibles, des pistes de réponse du manager et les erreurs à éviter."}];
let round=0,left=300,id=null;
const $=x=>document.getElementById(x);function show(x){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(x).classList.add('active')};function progress(x){$('progress').textContent=x}
function startBattle(){round=0;showRound()}function showRound(){let c=challenges[round];$('roundLabel').textContent=`DÉFI ${round+1} / 3`;$('title').textContent=c.title;$('situation').textContent=c.situation;$('mission').textContent=c.mission;$('help').classList.add('hidden');show('challenge');progress(`Défi ${round+1} / 3`);startTimer()}
function startTimer(){clearInterval(id);left=300;render();id=setInterval(()=>{left--;render();if(left<=0){clearInterval(id);$('timer').textContent='TEMPS !';$('timer').classList.add('warning');setTimeout(finishRound,650)}},1000)}function render(){let m=Math.floor(left/60).toString().padStart(2,'0'),s=(left%60).toString().padStart(2,'0');$('timer').textContent=`${m}:${s}`;$('timer').classList.toggle('warning',left<=60)}
function toggleHelp(){$('help').classList.toggle('hidden')}function finishRound(){clearInterval(id);$('selfLabel').textContent=`AUTO-ÉVALUATION — DÉFI ${round+1}`;show('selfcheck');progress(`Débrief du défi ${round+1}`);updateTotal()}function updateTotal(){let n=[...document.querySelectorAll('.scores select')].reduce((a,s)=>a+Number(s.value),0);$('total').textContent=n}document.querySelectorAll('.scores select').forEach(s=>s.addEventListener('change',updateTotal));function nextRound(){if(round<2){round++;showRound()}else{show('final');progress('Battle terminée')}}function restart(){clearInterval(id);show('home');progress('Accueil')}
